In [12]:
import pandas as pd

df = pd.read_csv('customer_shopping_behavior.csv')

df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 350.5 KB

In [15]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [16]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [19]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(
    lambda x: x.fillna(x.median())
)

In [20]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [23]:
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ','_')
df=df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [24]:
#create a column age_group
labels=['Young Adult','Adult','Middle-aged','Senior']
df['age_group']=pd.qcut(df['age'],q=4,labels=labels)
df[['age','age_group']].head(10)

   age    age_group
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged
5   46  Middle-aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle-aged

In [25]:
#create column purchase_frequency_days
frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

df[['purchase_frequency_days', 'frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually
5                        7                 Weekly
6                       90              Quarterly
7                        7                 Weekly
8                      365               Annually
9                       90              Quarterly

In [26]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [27]:
df=df.drop('promo_code_used',axis=1)
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='str')

In [30]:
import os
import sqlite3

database = "customer_behavior.db"

# Close old connection if it exists
try:
    connection.close()
except:
    pass

# Delete the corrupted database
if os.path.exists(database):
    os.remove(database)
    print("Old database deleted.")

# Create a fresh SQLite database
connection = sqlite3.connect(database)

print("New database created successfully.")

Old database deleted.
New database created successfully.

In [33]:
import sqlite3
import pandas as pd

# ==========================================
# 1. CREATE A FRESH SQLITE DATABASE
# ==========================================

connection = sqlite3.connect(":memory:")

print("SQLite database created successfully!")


# ==========================================
# 2. CHECK YOUR DATA
# ==========================================

print("\nData Preview:")
print(df.head())

print("\nShape of Data:")
print(df.shape)


# ==========================================
# 3. LOAD DATA INTO CUSTOMER TABLE
# ==========================================

table_name = "customer"

df.to_sql(
    table_name,
    connection,
    if_exists="replace",
    index=False
)

print("\nData successfully loaded into 'customer' table!")


# ==========================================
# 4. CHECK TABLE
# ==========================================

tables = pd.read_sql(
    "SELECT name FROM sqlite_master WHERE type='table';",
    connection
)

print("\nTables:")
print(tables)


# ==========================================
# 5. CHECK DATA FROM SQLITE
# ==========================================

result = pd.read_sql(
    "SELECT * FROM customer LIMIT 10;",
    connection
)

print("\nData from SQLite:")
print(result)

SQLite database created successfully!

Data Preview:
   customer_id  age gender item_purchased  category  purchase_amount  \
0            1   55   Male         Blouse  Clothing               53
1            2   19   Male        Sweater  Clothing               64
2            3   50   Male          Jeans  Clothing               73
3            4   21   Male        Sandals  Footwear               90
4            5   45   Male         Blouse  Clothing               49

        location size      color  season  review_rating subscription_status  \
0       Kentucky    L       Gray  Winter            3.1                 Yes
1          Maine    L     Maroon  Winter            3.1                 Yes
2  Massachusetts    S     Maroon  Spring            3.1                 Yes
3   Rhode Island    M     Maroon  Spring            3.5                 Yes
4         Oregon    M  Turquoise  Spring            2.7                 Yes

   shipping_type discount_applied  previous_purchases payment_method  \
0        Express              Yes                  14          Venmo
1        Express              Yes                   2           Cash
2  Free Shipping              Yes                  23    Credit Card
3   Next Day Air              Yes                  49         PayPal
4  Free Shipping              Yes                  31         PayPal

  frequency_of_purchases    age_group  purchase_frequency_days
0            Fortnightly  Middle-aged                       14
1            Fortnightly  Young Adult                       14
2                 Weekly  Middle-aged                        7
3                 Weekly  Young Adult                        7
4               Annually  Middle-aged                      365

Shape of Data:
(3900, 19)

Data successfully loaded into 'customer' table!

Tables:
       name
0  customer

Data from SQLite:
   customer_id  age gender item_purchased     category  purchase_amount  \
0            1   55   Male         Blouse     Clothing               53
1            2   19   Male        Sweater     Clothing               64
2            3   50   Male          Jeans     Clothing               73
3            4   21   Male        Sandals     Footwear               90
4            5   45   Male         Blouse     Clothing               49
5            6   46   Male       Sneakers     Footwear               20
6            7   63   Male          Shirt     Clothing               85
7            8   27   Male         Shorts     Clothing               34
8            9   26   Male           Coat    Outerwear               97
9           10   57   Male        Handbag  Accessories               31

        location size      color  season  review_rating subscription_status  \
0       Kentucky    L       Gray  Winter            3.1                 Yes
1          Maine    L     Maroon  Winter            3.1                 Yes
2  Massachusetts    S     Maroon  Spring            3.1                 Yes
3   Rhode Island    M     Maroon  Spring            3.5                 Yes
4         Oregon    M  Turquoise  Spring            2.7                 Yes
5        Wyoming    M      White  Summer            2.9                 Yes
6        Montana    M       Gray    Fall            3.2                 Yes
7      Louisiana    L   Charcoal  Winter            3.2                 Yes
8  West Virginia    L     Silver  Summer            2.6                 Yes
9       Missouri    M       Pink  Spring            4.8                 Yes

    shipping_type discount_applied  previous_purchases payment_method  \
0         Express              Yes                  14          Venmo
1         Express              Yes                   2           Cash
2   Free Shipping              Yes                  23    Credit Card
3    Next Day Air              Yes                  49         PayPal
4   Free Shipping              Yes                  31         PayPal
5        Standard              Yes                  14          Venmo
6   Free Shipping              Yes                  49           Cash
7   Free Shipping              Yes                  19    Credit Card
8         Express              Yes                   8          Venmo
9  2-Day Shipping              Yes                   4           Cash

  frequency_of_purchases    age_group  purchase_frequency_days
0            Fortnightly  Middle-aged                       14
1            Fortnightly  Young Adult                       14
2                 Weekly  Middle-aged                        7
3                 Weekly  Young Adult                        7
4               Annually  Middle-aged                      365
5                 Weekly  Middle-aged                        7
6              Quarterly       Senior                       90
7                 Weekly  Young Adult                        7
8               Annually  Young Adult                      365
9              Quarterly  Middle-aged                       90

In [34]:
print(df.columns.tolist())

['customer_id', 'age', 'gender', 'item_purchased', 'category', 'purchase_amount', 'location', 'size', 'color', 'season', 'review_rating', 'subscription_status', 'shipping_type', 'discount_applied', 'previous_purchases', 'payment_method', 'frequency_of_purchases', 'age_group', 'purchase_frequency_days']

In [35]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 19 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customer_id              3900 non-null   int64
 1   age                      3900 non-null   int64
 2   gender                   3900 non-null   str
 3   item_purchased           3900 non-null   str
 4   category                 3900 non-null   str
 5   purchase_amount          3900 non-null   int64
 6   location                 3900 non-null   str
 7   size                     3900 non-null   str
 8   color                    3900 non-null   str
 9   season                   3900 non-null   str
 10  review_rating            3900 non-null   float64
 11  subscription_status      3900 non-null   str
 12  shipping_type            3900 non-null   str
 13  discount_applied         3900 non-null   str
 14  previous_purchases       3900 non-null   int64
 15  payment_method           3900 non-null   str
 16  frequency_of_purchases   3900 non-null   str
 17  age_group                3900 non-null   category
 18  purchase_frequency_days  3900 non-null   int64
dtypes: category(1), float64(1), int64(5), str(12)
memory usage: 369.6 KB

In [36]:
pd.read_sql("PRAGMA table_info(customer);", connection)

    cid                     name     type  notnull dflt_value  pk
0     0              customer_id  INTEGER        0       None   0
1     1                      age  INTEGER        0       None   0
2     2                   gender     TEXT        0       None   0
3     3           item_purchased     TEXT        0       None   0
4     4                 category     TEXT        0       None   0
5     5          purchase_amount  INTEGER        0       None   0
6     6                 location     TEXT        0       None   0
7     7                     size     TEXT        0       None   0
8     8                    color     TEXT        0       None   0
9     9                   season     TEXT        0       None   0
10   10            review_rating     REAL        0       None   0
11   11      subscription_status     TEXT        0       None   0
12   12            shipping_type     TEXT        0       None   0
13   13         discount_applied     TEXT        0       None   0
14   14       previous_purchases  INTEGER        0       None   0
15   15           payment_method     TEXT        0       None   0
16   16   frequency_of_purchases     TEXT        0       None   0
17   17                age_group     TEXT        0       None   0
18   18  purchase_frequency_days  INTEGER        0       None   0

In [42]:

# ============================================================
# Q1. What is the total revenue generated by male vs. female?
# ============================================================

q1 = """
SELECT 
    gender,
    SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;
"""

q1_result = pd.read_sql_query(q1, connection)

print("Q1 RESULT")
display(q1_result)


# ============================================================
# Q2. Which customers used a discount but still spent more
#     than the average purchase amount?
# ============================================================

q2 = """
SELECT 
    customer_id,
    purchase_amount,
    discount_applied
FROM customer
WHERE discount_applied = 'Yes'
AND purchase_amount >= (
    SELECT AVG(purchase_amount)
    FROM customer
);
"""

q2_result = pd.read_sql_query(q2, connection)

print("\nQ2 RESULT")
display(q2_result)


# ============================================================
# Q3. Top 5 products with the highest average review rating
# ============================================================

q3 = """
SELECT 
    item_purchased,
    ROUND(AVG(review_rating), 2) AS "Average Product Rating"
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;
"""

q3_result = pd.read_sql_query(q3, connection)

print("\nQ3 RESULT")
display(q3_result)


# ============================================================
# Q4. Compare average Purchase Amounts between
#     Standard and Express Shipping
# ============================================================

q4 = """
SELECT 
    shipping_type,
    ROUND(AVG(purchase_amount), 2) AS average_purchase_amount
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;
"""

q4_result = pd.read_sql_query(q4, connection)

print("\nQ4 RESULT")
display(q4_result)


# ============================================================
# Q5. Do subscribed customers spend more?
#     Compare average spend and total revenue
# ============================================================

q5 = """
SELECT 
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS avg_spend,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC, avg_spend DESC;
"""

q5_result = pd.read_sql_query(q5, connection)

print("\nQ5 RESULT")
display(q5_result)


# ============================================================
# Q6. Which 5 products have the highest percentage
#     of purchases with discounts applied?
# ============================================================

q6 = """
SELECT 
    item_purchased,
    ROUND(
        100.0 * SUM(
            CASE 
                WHEN discount_applied = 'Yes' THEN 1 
                ELSE 0 
            END
        ) / COUNT(*),
        2
    ) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;
"""

q6_result = pd.read_sql_query(q6, connection)

print("\nQ6 RESULT")
display(q6_result)


# ============================================================
# Q7. Segment customers into New, Returning and Loyal
#     based on previous purchases
# ============================================================

q7 = """
WITH customer_type AS (
    SELECT 
        customer_id,
        previous_purchases,
        CASE 
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
)

SELECT 
    customer_segment,
    COUNT(*) AS "Number of Customers"
FROM customer_type
GROUP BY customer_segment;
"""

q7_result = pd.read_sql_query(q7, connection)

print("\nQ7 RESULT")
display(q7_result)


# ============================================================
# Q8. Top 3 most purchased products within each category
# ============================================================

q8 = """
WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)

SELECT 
    item_rank,
    category,
    item_purchased,
    total_orders
FROM item_counts
WHERE item_rank <= 3
ORDER BY category, item_rank;
"""

q8_result = pd.read_sql_query(q8, connection)

print("\nQ8 RESULT")
display(q8_result)


# ============================================================
# Q9. Are repeat buyers (>5 previous purchases)
#     also likely to subscribe?
# ============================================================

q9 = """
SELECT 
    subscription_status,
    COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;
"""

q9_result = pd.read_sql_query(q9, connection)

print("\nQ9 RESULT")
display(q9_result)


# ============================================================
# Q10. What is the revenue contribution of each age group?
# ============================================================

q10 = """
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;
"""

q10_result = pd.read_sql_query(q10, connection)

print("\nQ10 RESULT")
display(q10_result)

Q1 RESULT

   gender  revenue
0  Female    75191
1    Male   157890

Q2 RESULT

     customer_id  purchase_amount discount_applied
0              2               64              Yes
1              3               73              Yes
2              4               90              Yes
3              7               85              Yes
4              9               97              Yes
..           ...              ...              ...
834         1667               64              Yes
835         1671               73              Yes
836         1673               73              Yes
837         1674               62              Yes
838         1676               90              Yes

[839 rows x 3 columns]

Q3 RESULT

  item_purchased  Average Product Rating
0         Gloves                    3.86
1        Sandals                    3.84
2          Boots                    3.82
3            Hat                    3.80
4          Skirt                    3.78

Q4 RESULT

  shipping_type  average_purchase_amount
0       Express                    60.48
1      Standard                    58.46

Q5 RESULT

  subscription_status  total_customers  avg_spend  total_revenue
0                  No             2847      59.87       170436.0
1                 Yes             1053      59.49        62645.0

Q6 RESULT

  item_purchased  discount_rate
0            Hat          50.00
1       Sneakers          49.66
2           Coat          49.07
3        Sweater          48.17
4          Pants          47.37

Q7 RESULT

  customer_segment  Number of Customers
0            Loyal                 3116
1              New                   83
2        Returning                  701

Q8 RESULT

    item_rank     category item_purchased  total_orders
0           1  Accessories        Jewelry           171
1           2  Accessories     Sunglasses           161
2           3  Accessories           Belt           161
3           1     Clothing          Pants           171
4           2     Clothing         Blouse           171
5           3     Clothing          Shirt           169
6           1     Footwear        Sandals           160
7           2     Footwear          Shoes           150
8           3     Footwear       Sneakers           145
9           1    Outerwear         Jacket           163
10          2    Outerwear           Coat           161

Q9 RESULT

  subscription_status  repeat_buyers
0                  No           2518
1                 Yes            958

Q10 RESULT

     age_group  total_revenue
0  Young Adult          62143
1  Middle-aged          59197
2        Adult          55978
3       Senior          55763

In [43]:
df.to_csv("customer_cleaned.csv", index=False)

print("Cleaned data exported successfully!")

Cleaned data exported successfully!

In [44]:
from IPython.display import FileLink

FileLink("customer_cleaned.csv")

/drive/notebooks/customer_cleaned.csv